# this file is just to test git
print('Initial file')
print('this is coming from b2')
print('This is coming from branch b1')
print('this is coming from branch c of b1')
print('S2 modified S2')
print('This branch was changed in S1')
print('cool')
print('S11 S11 S11')
print('more changes coming from this stupid branch')
